name: flutter_widget_from_html_core
description: Flutter plugin for widget tree building from html.

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
